
--Initial data. Not valid for current tables

--INSERT INTO USER_ACCOUNT (ACCOUNT_NAME, DESCRIPTION, FIRST_NAME, FAMILY_NAME, PASSWORD) VALUES ('user', 'description', 'user_di', '12345');
--
--INSERT INTO USER_ACCOUNT (ACCOUNT_NAME, DESCRIPTION, FIRST_NAME, FAMILY_NAME, PASSWORD) VALUES ('admin', 'description', 'admin_di', '12345');
--
--INSERT INTO USER_ROLE (RNAME) VALUES ('USER');
--INSERT INTO USER_ROLE (RNAME) VALUES ('ADMIN');
--
--INSERT INTO user_role_lnk  VALUES (1,1);
--INSERT INTO user_role_lnk  VALUES (2,2);